/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author leont
 */
import java.io.File;
import org.apache.commons.io.FileUtils;
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        outPane = new javax.swing.JScrollPane();
        outArea = new javax.swing.JTextArea();
        outLbl = new javax.swing.JLabel();
        osInfo = new javax.swing.JButton();
        usernameBtn = new javax.swing.JButton();
        javaVerBtn = new javax.swing.JButton();
        userDirBtn = new javax.swing.JButton();
        jvmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diagnosis");

        mainPanel.setLayout(new java.awt.GridBagLayout());

        outPane.setPreferredSize(new java.awt.Dimension(280, 98));

        outArea.setColumns(20);
        outArea.setLineWrap(true);
        outArea.setRows(5);
        outArea.setWrapStyleWord(true);
        outPane.setViewportView(outArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(outPane, gridBagConstraints);

        outLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        outLbl.setText("Output:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(outLbl, gridBagConstraints);

        osInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        osInfo.setText("OS information");
        osInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osInfoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(osInfo, gridBagConstraints);

        usernameBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameBtn.setText("Username");
        usernameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(usernameBtn, gridBagConstraints);

        javaVerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        javaVerBtn.setText("Java version");
        javaVerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                javaVerBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(javaVerBtn, gridBagConstraints);

        userDirBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userDirBtn.setText("User folder information");
        userDirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDirBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(userDirBtn, gridBagConstraints);

        jvmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jvmBtn.setText("JVM information");
        jvmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jvmBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(jvmBtn, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameBtnMouseClicked
        String username = System.getProperty("user.name");
        outArea.setText("Username: " + username);
    }//GEN-LAST:event_usernameBtnMouseClicked

    private void osInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osInfoMouseClicked
        String osName = System.getProperty("os.name");
        String osArch = System.getProperty("os.arch");
        String osVer = System.getProperty("os.version");
        outArea.setText("OS name: " + osName + '\n' + 
                        "OS architecture: " + osArch + '\n' +
                        "OS version: " + osVer + '\n');
    }//GEN-LAST:event_osInfoMouseClicked

    private void javaVerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_javaVerBtnMouseClicked
        String javaSpecVer = System.getProperty("java.vm.specification.version");
        String javaImpVer = System.getProperty("java.vm.version");
        String javaReVer = System.getProperty("java.specification.version");
        outArea.setText("Java VM specification version: " + javaSpecVer + '\n' + 
                        "Java VM implementation version: " + javaImpVer + '\n' +
                        "Java RE specification version: " + javaReVer + '\n');
    }//GEN-LAST:event_javaVerBtnMouseClicked

    private void userDirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDirBtnMouseClicked
        String homeDir = System.getProperty("user.home");
        long dirSize = FileUtils.sizeOfDirectory(new File(homeDir));
        long dirSize2 = Long.divideUnsigned(dirSize, 1048576);
        outArea.setText("User's home directory: " + homeDir + '\n' + 
                        "Directory size: " + Long.toString(dirSize2) + " MB" + '\n');
    }//GEN-LAST:event_userDirBtnMouseClicked

    private void jvmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jvmBtnMouseClicked
        Runtime rt = Runtime.getRuntime();
        String jvmFreeMem = Long.toString(Long.divideUnsigned(rt.freeMemory(), 1048576));
        String jvmAllocMem = Long.toString(Long.divideUnsigned(rt.totalMemory(), 1048576));
        String jvmBeforeAllocMem = Long.toString(Long.divideUnsigned(rt.maxMemory(), 1048576));
        outArea.setText("JVM free memory: " + jvmFreeMem + " MB" + '\n' + 
                        "JVM total available memory: " + jvmAllocMem  + " MB" + '\n' +
                        "JVM max memory: " + jvmBeforeAllocMem + " MB" + '\n');
    }//GEN-LAST:event_jvmBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton javaVerBtn;
    private javax.swing.JButton jvmBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton osInfo;
    private javax.swing.JTextArea outArea;
    private javax.swing.JLabel outLbl;
    private javax.swing.JScrollPane outPane;
    private javax.swing.JButton userDirBtn;
    private javax.swing.JButton usernameBtn;
    // End of variables declaration//GEN-END:variables
}
